AMO_2/urls.py
from django.contrib import admin
from django.urls import path, include

from collect_macmenu.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('collect_macmenu/', include('collect_macmenu.urls', namespace='collect_macmenu')),
    path('display_macmenu/', include('display_macmenu.urls', namespace='display_macmenu')),
    path('__debug__/', include('debug_toolbar.urls')),
]

collect_macmenu/urls.py
from django.urls import path
from . import views

app_name = 'collect_macmenu'

urlpatterns = [
    path('', views.home, name='home'),
    path('collect_menu/', views.collect_menu, name='collect_menu'),
]

display_macmenu/urls.py
from django.urls import path
from . import views

app_name = 'display_macmenu'

urlpatterns = [
    path('all_products/', views.all_products, name='all_products'),
    path('products/<str:product_name>/', views.product, name='product'),
    path('products/<str:product_name>/<str:product_field>/', views.product_field, name='product_field')
]

macmenu_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('collect_macmenu/', include('collect_macmenu.urls', namespace='collect_macmenu')),
    path('__debug__/', include('debug_toolbar.urls')),
]

collect_macmenu/models.py
from django.db import models

# Create your models here.

display_macmenu/models.py
from django.db import models

# Create your models here.

collect_macmenu/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .services.selenium_service.macmenu_parse import MacMenu


def home(request):
    return render(request, 'home_page.html')


def collect_menu(request):
    menu = MacMenu()
    success = menu.save_mac_menu_as_json()
    return render(request, 'collect_menu.html', {'success': success})

display_macmenu/views.py
from django.shortcuts import render

from display_macmenu.services.display_services import get_products, get_product, get_field


def all_products(request):
    products = get_products()
    return render(request, 'all_products.html', {'products': products})


def product(request, product_name):
    concrete_product = get_product(product_name)
    return render(request, 'concrete_product.html', {'product': concrete_product})


def product_field(request, product_name, product_field):
    field = get_field(product_name, product_field)
    return render(request, 'concrete_product_field.html', {'field_name': product_field, 'field': field})

collect_macmenu/templates/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    {% bootstrap_css %}
    <link href="{% static "css/mac_menu_css.css" %}" rel="stylesheet">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'collect_macmenu:home' %}">Home</a>
            </nav>
        </div>
    </div>
    <div class="row center">
        <div class="col-12">
            {% block body %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

collect_macmenu/templates/collect_menu.html
{% extends 'basic.html' %}
{% block title %}{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                {% if success %}
                    Menu successfully parsed !!!
                {% else %}
                    Something went wrong :(
                    <a href="{% url 'collect_macmenu:collect_menu' %}">Retry</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

collect_macmenu/templates/home_page.html
{% extends 'basic.html' %}
{% block title %}Home{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-6">
                <a href="{% url 'collect_macmenu:collect_menu' %}" class="btn-lg center">collect MC Donald's menu</a>
            </div>
            <div class="col-6">
                <a href="{% url 'display_macmenu:all_products' %}" class="btn-lg center">Show MC Donald's menu</a>
            </div>
        </div>
    </div>
{% endblock %}

display_macmenu/templates/all_products.html
{% extends 'basic.html' %}
{% block title %}Menu{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <h1>Menu</h1>
            <div class="col-12">
                {% include 'includes/menu_display.html' %}
            </div>
        </div>
    </div>
{% endblock %}

display_macmenu/templates/concrete_product.html
{% extends 'basic.html' %}
{% load static %}
<link href="{% static "css/mac_menu_css.css" %}" rel="stylesheet">
{% block title %}{{ product.name }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="product">
                    {% if product %}
                        {% include 'includes/product_display.html' %}
                    {% else %}
                        <p>No Info about the product :\</p>
                        <a href="{% url 'collect_macmenu:collect_menu' %}" class="btn">Try to collect menu info</a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

display_macmenu/templates/concrete_product_field.html
{% extends 'basic.html' %}
{% block title %}{{ field }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <h1>{{ field_name }} Field Info</h1>
            <div class="col-12">
                <p>{{ field }}</p>
            </div>
        </div>
    </div>
{% endblock %}

display_macmenu/templates/includes/menu_display.html
<div class="container-fluid">
    <div class="row">
        {% for product in products %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <img src="{{ product.image_url }}" class="card-img-top" alt="product image">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                        <a href="{% url 'display_macmenu:product' product.name %}" class="btn btn-primary">More info</a>
                    </div>
                </div>
            </div>
            {% if forloop.counter|divisibleby:3 and not forloop.last %}
                </div>
                <div class="row">
            {% endif %}
        {% empty %}
            <div class="col-12"><p>No products yet, try to collect menu here:</p></div>
            <div class="col-12"><a href="{% url 'collect_macmenu:collect_menu' %}" class="btn btn-primary">collect
                menu</a></div>
        {% endfor %}
        </div>
</div>

display_macmenu/templates/includes/product_display.html
<a href="{% url 'display_macmenu:product_field' product.name 'name' %}"
      class="btn"><h2>{{ product.name }}</h2></a>
<a href="{% url 'display_macmenu:product_field' product.name 'image_url' %}">
    <img src="{{ product.image_url }}" alt="{{ product.name }} Image"></a>

<p><a href="{% url 'display_macmenu:product_field' product.name 'description' %}"
      class="btn">Description:</a> {{ product.description }}
</p>
<p><a href="{% url 'display_macmenu:product_field' product.name 'calories' %}"
      class="btn">Calories:</a> {{ product.calories }}</p>
<p><a href="{% url 'display_macmenu:product_field' product.name 'fats' %}"
      class="btn">Fats:</a> {{ product.fats }}</p>
<p><a href="{% url 'display_macmenu:product_field' product.name 'carbs' %}"
      class="btn">Carbs:</a> {{ product.carbohydrates }}</p>
<p><a href="{% url 'display_macmenu:product_field' product.name 'proteins' %}"
      class="btn">Proteins:</a> {{ product.proteins }}</p>
<p><a href="{% url 'display_macmenu:product_field' product.name 'unsaturated_fats' %}" class="btn">Unsaturated
    Fats:</a> {{ product.unsaturated_fats }}</p>
<p><a href="{% url 'display_macmenu:product_field' product.name 'sugar' %}"
      class="btn">Sugar:</a> {{ product.sugar }}</p>
<p><a href="{% url 'display_macmenu:product_field' product.name 'salt' %}"
      class="btn">Salt:</a> {{ product.salt }}</p>
<p><a href="{% url 'display_macmenu:product_field' product.name 'portion' %}"
      class="btn">Portion:</a> {{ product.portion }}</p>